#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh
prepare_testing_data


#-----------------------------------------------------------------------------------------
echo '------------------------ Testing amazon_download file --------------------------'
amazon_download.py --study-name=TEST_STUDY --located-files=blockMeshDict --output-dir='case.out' $* > log.amazon_download_file 2>&1

if [ $? -ne 0 ]; then
   echo "An error have appeared during execution of amazon_dwonload.py" 
   cat log.amazon_download_file
   rm log.amazon_download_file
else
  if [ -f case.out/blockMeshDict ]; then
     echo '----------------------------------- OK -----------------------------------------'
  else
     echo ' ERROR : There is no downloading file , in "case.out" folder '
     rm log.amazon_download_file
  fi
fi

