#!/bin/bash

#-----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh
prepare_testing_data


#-----------------------------------------------------------------------------------------
echo '------------------------ Testing amazon_download study -------------------------'
amazon_download.py --study-name=TEST_STUDY --output-dir='case.out' --enable-fresh $* > log.amazon_download_study 2>&1

if [ $? -ne 0 ]; then
   echo "An error have appeared during execution of amazon_dwonload.py" 
   cat log.amazon_download_study
   rm log.amazon_download_study
else
  if [[ -f case.out/blockMeshDict && -f case.out/boundary && -f case.out/faces && -f case.out/neighbour ]]; then
     echo '----------------------------------- OK -----------------------------------------'
  else
     echo ' ERROR : There are not all downloading files , in "case.out" folder '
     rm log.amazon_download_study
  fi
fi

