#!/bin/bash

if [ -f 'log.prepare_test_case' ]; then
   echo ''
else
   ./prepare_testing_data
   echo ''
fi


echo '-------------------------- Testing amazon_ls studies -----------------------------'
amazon_ls.py $* > log.amazon_ls_study 2>&1

if [ $? -ne 0 ] ; then
   echo "An error have appeared during execution of amazon_ls.py" 
   cat log.amazon_ls_study
   rm log.amazon_ls_study
else
   count=`fgrep -c "TEST_STUDY" log.amazon_ls_study`
   if [ ${count} -gt 0 ] ; then 
      echo '----------------------------------- OK ------------------------------------------'
   else
      echo ' ERROR : There is no "TEST_STUDY" in the s3 '
      rm log.amazon_ls_study
   fi   

fi

