#!/bin/bash

#-----------------------------------------------------------------------------------------
#source common function
. common.sh
prepare_testing_data


#-----------------------------------------------------------------------------------------
echo '------------------------ Testing amazon_download study -------------------------'
amazon_download.py --study-name=TEST_STUDY --output-dir='case.out' --enable-fresh $* > log.amazon_download_study 2>&1

if [ $? -ne 0 ]; then
   echo "An error have appeared during execution of amazon_dwonload.py" 
   cat log.amazon_download_study
   rm log.amazon_download_study
else
  if [[ -f case.out/blockMeshDict && -f case.out/boundary && -f case.out/faces && -f case.out/neighbour ]]; then
     echo '----------------------------------- OK -----------------------------------------'
  else
     echo ' ERROR : There are not all downloading files , in "case.out" folder '
     rm log.amazon_download_study
  fi
fi

