#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh
prepare_testing_data


#-----------------------------------------------------------------------------------------
echo '-------------------------- Testing amazon_ls files -----------------------------'
amazon_ls.py TEST_STUDY $* > log.amazon_ls_files 2>&1

if [ $? -ne 0 ] ; then
   echo "An error have appeared during execution of amazon_ls.py" 
   cat log.amazon_ls_files
   rm log.amazon_ls_files
else
   count_boundary=`fgrep -c "boundary" log.amazon_ls_files`
   count_blockMeshDict=`fgrep -c "blockMeshDict" log.amazon_ls_files`
   count_faces=`fgrep -c "faces" log.amazon_ls_files`
   count_neighbour=`fgrep -c "faces" log.amazon_ls_files`
   if [[ ${count_boundary} -gt 0 && ${count_blockMeshDict} -gt 0 && ${count_faces} -gt 0 && ${count_neighbour} -gt 0 ]] ; then 
      echo '----------------------------------- OK -----------------------------------------'
   else
      echo ' ERROR : There are not all files in the s3 '
      rm log.amazon_ls_files
   fi   

fi


#-----------------------------------------------------------------------------------------
