#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh
a_study_name=`prepare_testing_data`


#-----------------------------------------------------------------------------------------
an_output_dir=${case_dir}.out
a_list_filenames=`create_list_filenames_in_casedir`
a_downloading_file=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 2 ]" `

echo '------------------------ Testing amazon_download file --------------------------'
amazon_download.py --study-name=${a_study_name} --located-files=${a_downloading_file} --output-dir=${an_output_dir} $* > log.amazon_download_file 2>&1

if [ $? -ne 0 ]; then
   echo "An error have appeared during execution of amazon_dwonload.py" 
   cat log.amazon_download_file
   rm log.amazon_download_file
else
   if [ -f ${an_output_dir}/${a_downloading_file} ]; then
      echo '----------------------------------- OK -----------------------------------------'
   else
      echo " ERROR : There is no downloading file '${a_downloading_file}' , in '${an_output_dir}' folder "
      rm log.amazon_download_file
   fi
fi

