#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh
a_study_name=`create_study_name`


#-----------------------------------------------------------------------------------------
an_output_dir=${case_dir}.out

echo '------------------------ Testing amazon_upload folder --------------------------'
dummy=`amazon_upload_start.py --study-name=${a_study_name} ${case_dir} 2>log.amazon_upload_folder | amazon_upload_resume.py  2>>log.amazon_upload_folder`
if [ $? -ne 0 ]; then
   echo "An error have appeared during execution of amazon_upload_start.py | amazon_upload_resume.py" 
   cat log.amazon_upload_folder
   rm log.amazon_upload_folder
   exit -1
else
   dummy=`amazon_ls.py ${a_study_name} >log.check_upload_folder 2>&1`
   count_entrances=`fgrep -c ${case_dir} log.check_upload_folder`
   if [ ${count_entrances} -ne 0 ]; then
      echo '----------------------------------- OK -----------------------------------------'
      rm log.check_upload_folder
   else
      echo " ERROR : There is no uploading file '${case_dir}' , in the s3 "
      rm log.amazon_download_file
      exit -1
   fi
fi

echo '----------------------- Testing amazon_download folder -------------------------'
amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} > log.amazon_download_folder 2>&1
if [ $? -ne 0 ]; then
   echo "An error have appeared during execution of amazon_download.py" 
   cat log.amazon_download_folder
   rm log.amazon_download_folder
   exit -1
else
   a_differences=`diff -r -q -i -x "*~" ${case_dir} ${an_output_dir}/${case_dir}`
   if [ "x${a_differences}" == "x" ]; then
      echo '----------------------------------- OK -----------------------------------------'   
      dummy=`amazon_rm_study.py ${a_study_name} > log.tmp 2>&1`
      rm log.tmp
   else
      echo "ERROR: There are differences between '${case_dir}' and '${an_output_dir}/${case_dir}': " 
      echo ${a_differences}
      exit -1
   fi
fi
