#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh
a_study_name=`prepare_testing_data`


#-----------------------------------------------------------------------------------------
echo '-------------------------- Testing amazon_ls files -----------------------------'
amazon_ls.py ${a_study_name} > log.amazon_ls_files 2>&1

if [ $? -ne 0 ] ; then
   echo "An error have appeared during execution of amazon_ls.py" 
   cat log.amazon_ls_files
   rm log.amazon_ls_files
   exit -1
else
   an_allright="True"
   a_list_filenames=`create_list_filenames_in_casedir`
   for a_filename in ${a_list_filenames}
   do
      count_entrances=`fgrep -c ${a_filename} log.amazon_ls_files`
      if [ ${count_entrances} -eq 0 ]; then
         an_allright="False"
         a_not_exists_file=${a_filename}
         break
      fi
   done 
   if [ "${an_allright}" = "False" ]; then
      echo " ERROR : There is no '${a_not_exists_file}' file in the s3 "
      rm log.amazon_ls_files
      exit -1
   else
      echo '----------------------------------- OK -----------------------------------------'
   fi
fi


#-----------------------------------------------------------------------------------------
