#!/usr/bin/env bash

#--------------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # run from this directory
set -x


#--------------------------------------------------------------------------------------
a_hostname=`hostname`
wmake exe 1>./log.cout.wmake.${a_hostname} 2>./log.cerr.wmake.${a_hostname} || errorcode=$?

cat log.cout.wmake.${a_hostname} > ./log.wmake.${a_hostname}
cat log.cerr.wmake.${a_hostname} >> ./log.wmake.${a_hostname}

if [ "${errorcode}x" != "x" ] ; then
    echo "ERROR"
    exit ${errorcode}
fi


# To extract the target application name
application=`cat ./Make/files | grep SEXE | sed -e"s%\([^/]*\)/\(.*\)%\2%g"`

echo ${application}


#--------------------------------------------------------------------------------------
