#!/bin/sh

#--------------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # run from this directory
set -x


#--------------------------------------------------------------------------------------
wmake exe 1>./cout.wmake 2>./cerr.wmake || errorcode=$?

cat cout.wmake > ./log.wmake
cat cerr.wmake >> ./log.wmake

if [ ${errorcode} != 0 ] ; then
    echo "ERROR"
    exit ${errorcode}
fi
 

# To extract the target application name
application=`cat ./Make/files | grep SEXE | sed -e"s%\([^/]*\)/\(.*\)%\2%g"`

echo ${application}


#--------------------------------------------------------------------------------------
