#!/usr/bin/env bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## See http://sourceforge.net/apps/mediawiki/cloudflu
##
## Author : Alexey Petrov
##


#--------------------------------------------------------------------------------------
the_case=`python -c "from sys import argv; print argv[ len( argv ) - 1 ]" $*`

the_other=`python -c "from sys import argv; print argv[ 1 : len( argv ) - 1 ]" $*`
the_other=`bash -c "echo ${the_other} | sed -e's%\[%%' -e's%,%%g' -e's%]%%'"`

# a_case_name=`basename ${the_case}`
# paraview --data="${the_case}/VTK/${a_case_name}_..vtk" ${the_other} &


#--------------------------------------------------------------------------------------
