#!/usr/bin/env bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## See http://sourceforge.net/apps/mediawiki/cloudflu
##
## Author : Alexey Petrov
##


#--------------------------------------------------------------------------------------
case  $* in 
    '-h' | '--help' | '--version' ) cloudflu-reservation-run $* | sed -e's%cloudflu-reservation-run%cloudflu-cluster-start%g' ;;
    * ) a_cluster_id=`cloudflu-reservation-run $* | cloudflu-openmpi-config | cloudflu-nfs-config`
        echo ${a_cluster_id} | cloudflu-instance-extract | cloudflu-credentials-deploy | cloudflu-deploy > /dev/null
        echo ${a_cluster_id} ;;
esac



#--------------------------------------------------------------------------------------
