#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./ec2.sh


#-----------------------------------------------------------------------------------------
a_list_file_reservations=`ls reservations_* 2>log.tmp`
for a_file_reservation in ${a_list_file_reservations} ; do
    if [ -f  ${a_file_reservation} ]; then
	a_reservation=`get_reservation ${a_file_reservation} `
	
	if [ "x${a_reservation}" != "x" ];then
	    a_region=`echo ${a_file_reservation} | awk "-F_" '{print $3}'`
            export __BALLOON_IMAGE_LOCATION__=''
	    
	    if [ "x${a_region}" != "x" ]; then
               export __BALLOON_IMAGE_LOCATION__=${a_region}
	    fi
	    
	    process_script "amazon_reservation_delete.py ${a_reservation}"
	fi
	rm  ${a_file_reservation}
    fi
done


#-----------------------------------------------------------------------------------------
amazon_ls.py | grep tmp- | xargs amazon_rm_study.py

rm -fr *~ damBreak.out*  log.*


#-----------------------------------------------------------------------------------------
