#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
. ec2.sh


#-----------------------------------------------------------------------------------------
a_list_file_reservations=`ls reservations_* 2>log.tmp`
for a_file_reservation in ${a_list_file_reservations}
do
  if [ -f  ${a_file_reservation} ]; then
     a_reservation=`get_reservation ${a_file_reservation} `
     if [ "x${a_reservation}" != "x" ];then
        an_image_location=`get_image_location ${a_reservation}`
        a_reservation_id=`get_reservation_id ${a_reservation}`
        an_indentity_file=`get_identity_file ${a_reservation}`
        amazon_reservation_delete.py --image-location=${an_image_location} --reservation-id=${a_reservation_id} --identity-file=${an_indentity_file} --debug
        if [ $? -ne 0 ]; then
           echo ''
           echo "--------------------------------------------------------------------------------"
           echo "An error have appeared during execution of"
           echo "amazon_reservation_delete.py --image-location=${an_image_location} --reservation-id=${a_reservation_id} --identity-file=${an_indentity_file} --debug" 
           echo "--------------------------------------------------------------------------------"
           exit -1
        fi
    fi
    rm  ${a_file_reservation}
  fi
done

amazon_ls.py 2>log.txt | grep tmp- | xargs amazon_rm_study.py 2>>log.txt
rm -f log.*
rm -f *~
rm -rf damBreak.out*


