#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./ec2.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0

  prepare_reservation ${instance_type} && a_reservation=`get_result`
  process_script "echo ${a_reservation} | balloon-openmpi-config --debug"
  process_script "echo ${a_reservation} | balloon-nfs-config --debug"

  process_script "echo ${a_reservation} | balloon-instance-extract --debug" && an_instance=`get_result`
  process_script "echo ${an_instance} | balloon-deploy-credentials --debug"
  process_script "echo ${an_instance} | balloon-deploy --debug --production"

  process_script "amazon_solver_run.py --debug --case-dir=damBreak --output-suffix=.out1 ${a_reservation}" ${a_script_name}

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test_hook


#-----------------------------------------------------------------------------------------
