#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./ec2.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0

  a_region='us-east-1'
  an_image_id='ami-ecf50385'
  prepare_reservation ${TEST_CLOUDFLU_INSTANCE_TYPE} ${a_region} ${an_image_id} && a_reservation=`get_result`
  process_script "echo '${a_reservation}' | cloudflu-openmpi-config | cloudflu-nfs-config"

  process_script "echo '${a_reservation}' | cloudflu-instance-extract" && an_instance=`get_result`
  process_script "echo ${an_instance} | cloudflu-credentials-deploy | cloudflu-deploy --production --url='${__CLOUDFLU_DEPLOY_URL__}'"

  # process_script "cloudflu-study-book | tee >(cloudflu-solver-process --output-dir='damBreak.out') | cloudflu-solver-start <(echo '${a_reservation}') --case-dir='damBreak'"
  # Because of 'tee' utility runs its subprocesses in asynchronic way, to assure the accomplishement of the whole porcess tree, 
  # 'pipe' notion is used (mkfifo creates a named 'pipe')
  a_case_dir=${TEST_CLOUDFLU_EC2_CASES}/damBreak
  an_output_dir=${a_case_dir}.out
  process_script "mkfifo $$ && cloudflu-study-book | tee >(cloudflu-solver-process --output-dir=${an_output_dir} >$$) | cloudflu-solver-start <(echo '${a_reservation}') --case-dir=${a_case_dir} | cat $$ && rm $$"
 
  if [ ! -e ${an_output_dir}/log.solver ]; then
     process_error "There is no solver log 'log.InterFoam.cloudflu' in '${an_output_dir}' folder"
  fi
  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test_hook


#-----------------------------------------------------------------------------------------
