#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. s3.sh


#-----------------------------------------------------------------------------------------
testing_rm_files()
{
  a_script_name=`basename $0`
  a_study_name=`prepare_testing_data`

  echo "---------------------- Running \"${a_path_script}/${a_script_name}\" -------------------------"
  a_list_filenames=`create_list_filenames_in_casedir`
  a_list_file_to_rm=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 1 ],' ',_list[ 0 ]" `

  a_testing_script="amazon_rm.py --study-name=${a_study_name}  ${a_list_file_to_rm} --debug"
  ${a_testing_script} > log.${a_script_name} 2>&1
  if [ $? -ne 0 ] ; then
     echo ''
     echo ''
     echo "An error have appeared during execution of" 
     echo ${a_testing_script}
     echo "--------------------------------------------------------------------------------"
     echo ''
     echo ''
     cat log.${a_script_name}
     rm log.${a_script_name}
     exit -1
  else
     amazon_ls.py ${a_study_name} --debug > log.list_files 2>&1
     an_allright="True"
     for a_file in ${a_list_file_to_rm}
     do
        count_entrances=`fgrep -c ${a_file}  log.list_files `
        if [ ${count_entrances} -ne 0 ]; then
           an_allright="False"
           a_not_deleted_file=${a_filename}
           break
        fi 
     done
     if [ "${an_allright}" = "False" ]; then
        echo ''
        echo ''
        echo "--------------------------------------------------------------------------------"
        echo ' ERROR : The '${a_not_deleted_file}' file have not been removed from the s3 '
        echo "--------------------------------------------------------------------------------"
        echo ''
        echo ''
        rm log.list_files
        cat log.${a_script_name}
        rm log.${a_script_name}
        exit -1
     else
        echo '----------------------------------- OK -----------------------------------------'
        rm log.list_files 
        `remove_log_prepare_test_case`
     fi
  fi
}


#-----------------------------------------------------------------------------------------
run_script testing_rm_files
