#!/bin/bash

#-----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  an_output_dir=${case_dir}.out
  
  a_list_filenames=`create_list_filenames_in_casedir`
  a_testing_filename=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 2 ]"`
  a_file="${case_dir}/${a_testing_filename}"

  a_study_name=`create_study_name`
  a_filelocation="test"
   
  process_script "balloon-study-book --study-name=${a_study_name} | amazon_upload_start.py ${a_file} --file-location=${a_filelocation} | amazon_upload_resume.py"

  a_testing_script="amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --located-files=${a_filelocation}/${a_testing_filename}"
  process_script "${a_testing_script}"
  
  
  if [ ! -e ${an_output_dir}/${a_filelocation}/${a_testing_filename} ]; then
     process_error "There is no '${a_testing_filename}' file, in output folder '${an_output_dir}/${a_filelocation}'"
  else
     process_script "amazon_rm_study.py ${a_study_name}"
  fi  

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test_hook


#-----------------------------------------------------------------------------------------
