#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh


#-----------------------------------------------------------------------------------------
testing_ls_studies()
{
  a_script_name=`basename $0`
  a_study_name=`prepare_testing_data`

  echo "-------------------- Running \"${a_path_script}/${a_script_name}\" -----------------------"
  a_testing_script="amazon_ls.py --debug"
  ${a_testing_script} > log.${a_script_name} 2>&1

  if [ $? -ne 0 ] ; then
     echo "An error have appeared during execution "
     echo ${a_testing_script}
     echo "--------------------------------------------------------------------------------"
     cat log.${a_script_name}
     rm log.${a_script_name}
     exit -1
  else
     count=`fgrep -c "${a_study_name}" log.${a_script_name}`
     if [ ${count} -gt 0 ] ; then 
        echo '----------------------------------- OK -----------------------------------------'
     else
        echo " ERROR : There is no '${a_study_name}' study in the s3 "
        rm log.${a_script_name}
        exit -1
     fi   
  fi
}


#-----------------------------------------------------------------------------------------
run_script testing_ls_studies
