#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. s3.sh


#-----------------------------------------------------------------------------------------
testing_ls_pipe_rm_studies()
{
  a_script_name=`basename $0`
  a_study_name1=`prepare_testing_data`
  `remove_log_prepare_test_case`
  a_study_name2=`prepare_testing_data`
  a_begin_study_name=`study_name_starts_with`

  echo "----------------- Running \"${a_path_script}/${a_script_name}\" --------------------"

  a_testing_script="amazon_ls.py --debug 2>log.${a_script_name} | grep -e ${a_study_name1} -e ${a_study_name2} | xargs amazon_rm_study.py --debug 2>>log.${a_script_name}"
  `bash -c "${a_testing_script}"`
  if [ $? -ne 0 ]; then
     echo ''
     echo ''
     echo "--------------------------------------------------------------------------------"
     echo "An error have appeared during execution of"
     echo ${a_testing_script}
     echo "--------------------------------------------------------------------------------"
     echo ''
     echo ''
     cat log.${a_script_name}
     rm log.${a_script_name}
     exit -1
  else
     dummy=`amazon_ls.py --debug 2>log.check_ls_pipe_rm_studies`
     count_entrances=`fgrep -c -e ${a_study_name1} -e ${a_study_name2} log.check_ls_pipe_rm_studies`
     if [ ${count_entrances} -ne 0 ]; then
        echo ''
        echo ''
        echo "--------------------------------------------------------------------------------"
        echo " ERROR : There is study named ${a_study_name1} or ${a_study_name2} ( may be both ) in the s3 "
        echo "--------------------------------------------------------------------------------"
        echo ''
        echo ''
        cat log.${a_script_name}
        rm log.${a_script_name}
     else
        echo '----------------------------------- OK -----------------------------------------'
        rm log.check_ls_pipe_rm_studies
        `remove_log_prepare_test_case`
        `rm_from_studies ${a_study_name1} ${a_study_name2}`
     fi
  fi
}

#-----------------------------------------------------------------------------------------
run_script testing_ls_pipe_rm_studies
