#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh


#-----------------------------------------------------------------------------------------
testing_upload_dwonload_folder()
{
  a_script_name=`basename $0`
  a_study_name=`create_study_name`

  an_output_dir=${case_dir}.out

  echo "-------- Running \"${a_path_script}/${a_script_name}\" upload folder -----------"
  
  a_testing_script="amazon_upload_start.py --study-name=${a_study_name} ${case_dir} --debug 2>log.${a_script_name} | amazon_upload_resume.py --debug  2>>log.${a_script_name}"
  dummy=`bash -c "${a_testing_script}"`
  if [ $? -ne 0 ]; then
     echo ''
     echo ''
     echo "An error have appeared during execution of " 
     echo ${a_testing_script}
     echo "--------------------------------------------------------------------------------"
     echo ''
     echo ''
     cat log.${a_script_name}
     rm log.${a_script_name}
     exit -1
  else
     dummy=`amazon_ls.py ${a_study_name} --debug >log.check_upload_folder 2>&1`
     count_entrances=`fgrep -c ${case_dir} log.check_upload_folder`
     if [ ${count_entrances} -ne 0 ]; then
        echo '----------------------------------- OK -----------------------------------------'
        rm log.check_upload_folder
        echo '----------------------------------------------------------------------------' > log.${a_script_name}
     else
        echo ''
        echo ''
        echo " ERROR : There is no uploading file '${case_dir}' , in the s3 "
        echo '----------------------------------------------------------------------------'
        echo ''
        echo ''
        cat log.${a_script_name}
        rm log.${a_script_name}
        exit -1
     fi
  fi

  echo "------ Running \"${a_path_script}/${a_script_name}\" to download folder --------"
  a_testing_script="amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --debug --enable-fresh"
  ${a_testing_script} >> log.${a_script_name}  2>&1
  
  if [ $? -ne 0 ]; then
     echo ''
     echo ''
     echo "An error have appeared during execution of" 
     echo ${a_testing_script}
     echo "--------------------------------------------------------------------------------"
     echo ''
     echo ''
     cat log.${a_script_name}
     rm log.${a_script_name}
     exit -1
  else
     a_differences=`diff -r -q -i -x "*~" ${case_dir} ${an_output_dir}/${case_dir}`
     if [ "x${a_differences}" == "x" ]; then
        echo '----------------------------------- OK -----------------------------------------'   
        dummy=`amazon_rm_study.py ${a_study_name} > log.tmp 2>&1`
        rm log.tmp
     else
        echo ''
        echo ''
        echo "ERROR: There are differences between '${case_dir}' and '${an_output_dir}/${case_dir}': " 
        echo ${a_differences}
        echo "--------------------------------------------------------------------------------"
        echo ''
        echo ''
        cat log.${a_script_name}
        rm log.${a_script_name}
        exit -1
     fi
  fi
}



#-----------------------------------------------------------------------------------------
run_script testing_upload_dwonload_folder
