#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  an_output_dir=${case_dir}.out

  a_study_name=`create_study_name`
  process_script "cloudflu-study-book --study-name=${a_study_name} | cloudflu-upload-start ${case_dir} | cloudflu-upload-resume"

  a_results=`amazon_ls.py ${a_study_name} 2>&1`
  count_entrances=`echo ${a_results} | grep -c ${case_dir}`

  if [ ${count_entrances} -eq 0 ]; then
      process_error "There is no uploading file '${case_dir}', in the S3"
  fi

  process_script "amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --fresh"

  a_differences=`diff -r -q -i -x "*~" ${case_dir} ${an_output_dir}/${case_dir}`
  if [ "x${a_differences}" == "x" ]; then
      amazon_rm_study.py ${a_study_name} > /dev/null 2>&1
  else
      process_error "There are differences between '${case_dir}' and '${an_output_dir}/${case_dir}':\n${a_differences}"
  fi

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test_hook


#-----------------------------------------------------------------------------------------
