#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh


#-----------------------------------------------------------------------------------------
test()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  an_output_dir=${case_dir}.out
  prepare_testing_data && a_study_name1=`get_result`

  process_script "balloon-study-book --debug --study-name=${a_study_name} | amazon_upload_start.py ${case_dir} --debug | amazon_upload_resume.py --debug"

  amazon_ls.py ${a_study_name} --debug >log.check_upload_folder 2>&1
  count_entrances=`fgrep -c ${case_dir} log.check_upload_folder`
  rm log.check_upload_folder
  if [ ${count_entrances} -eq 0 ]; then
      cat log.${a_script_name}
      rm log.${a_script_name}
      echo "--------------------------------------------------------------------------------"
      echo " ERROR : There is no uploading file '${case_dir}' , in the s3 "
      echo "--------------------------------------------------------------------------------"
      exit -1
  fi

  process_script "amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --debug --fresh"

  a_differences=`diff -r -q -i -x "*~" ${case_dir} ${an_output_dir}/${case_dir}`
  if [ "x${a_differences}" == "x" ]; then
      amazon_rm_study.py ${a_study_name} > log.tmp 2>&1
      rm log.tmp
  else
      cat log.${a_script_name}
      rm log.${a_script_name}
      echo "--------------------------------------------------------------------------------"
      echo "ERROR: There are differences between '${case_dir}' and '${an_output_dir}/${case_dir}': " 
      echo ${a_differences}
      echo "--------------------------------------------------------------------------------"
      exit -1
  fi

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test


#-----------------------------------------------------------------------------------------
