#!/bin/bash

#-----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh

export __CLOUDFLU_ARG_LIST_SEPARATOR__=':' #( only for testing )

#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  an_output_dir=${case_dir}.out

  a_list_filenames=`create_list_filenames_in_casedir`
  a_testing_filename1=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 2 ]"`
  a_testing_filename2=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 1 ]"`
  a_files=`create_list_case_files ${a_testing_filename1} ${a_testing_filename2}`

  a_study_name=`create_study_name`
  a_filelocation1="test1"
  a_filelocation2="test2" 
  process_script "cloudflu-study-book --study-name=${a_study_name} | cloudflu-upload-start ${a_files} --file-location=${a_filelocation1}:${a_filelocation2} | cloudflu-upload-resume"

  process_script "cloudflu-download --study-name=${a_study_name} --output-dir=${an_output_dir} --located-files=${a_filelocation1}/${a_testing_filename1}:${a_filelocation2}/${a_testing_filename2}"

  an_allright="True"
  for a_file in ${a_filelocation1}/${a_testing_filename1} ${a_filelocation2}/${a_testing_filename2}; do
     if [ ! -e ${an_output_dir}/${a_file} ]; then
        an_allright="False"
        a_bad_file=`basename ${a_file}`
        a_location_bad_file=${an_output_dir}/`dirname ${a_file}`
        break
     fi
  done
  
  if [ "${an_allright}" = "False" ]; then
     process_error "There is no '${a_bad_file}' file, in output folder '${a_location_bad_file}'"
  else
     process_script "amazon_rm_study.py ${a_study_name}"
  fi  

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test_hook


#-----------------------------------------------------------------------------------------
