#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh


#-----------------------------------------------------------------------------------------
test()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  prepare_testing_data && a_study_name1=`get_result`

  process_script "amazon_ls.py --debug"

  count=`fgrep -c "${a_study_name}" log.${a_script_name}`
  if [ ${count} -eq 0 ] ; then 
      cat log.${a_script_name}
      rm log.${a_script_name}
      echo "--------------------------------------------------------------------------------"
      echo " ERROR : There is no '${a_study_name}' study in the s3 "
      echo "--------------------------------------------------------------------------------"
      exit -1
  fi

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test


#-----------------------------------------------------------------------------------------
