#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  prepare_new_testing_data && a_study_name=`get_result`
  a_list_filenames=`create_list_filenames_in_casedir`
  a_list_file_to_rm=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 1 ],' ',_list[ 0 ]" `

  process_script "amazon_rm.py --study-name=${a_study_name} ${a_list_file_to_rm}" 

  a_results=`cloudflu-ls ${a_study_name} 2>&1`
  an_allright="True"
  for a_file in ${a_list_file_to_rm} ; do
      count_entrances=`echo ${a_results} | grep -c ${a_file}`
      if [ ${count_entrances} -ne 0 ]; then
          an_allright="False"
          a_not_deleted_file=${a_file}
          break
      fi 
  done

  if [ "${an_allright}" = "False" ]; then
      process_error "The '${a_not_deleted_file}' file have not been removed from the S3"
  else
      amazon_rm_study.py ${a_study_name} > /dev/null 2>&1
      unregister_study ${file_studies_starts}_ ${a_study_name}
  fi

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test_hook


#-----------------------------------------------------------------------------------------
