#!/bin/bash

#-----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  an_output_dir=${case_dir}.out
  
  prepare_testing_data && a_study_name=`get_result`
  
  a_testing_script="(balloon-study-seal --study-name=${a_study_name} 2>/dev/null &) && amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --wait 2>/dev/null"
  process_script "${a_testing_script}"
  
  a_list_filenames=`create_list_filenames_in_casedir`
  an_allright="True"
  for a_file in ${a_list_filenames} ; do
      if [ ! -e ${an_output_dir}/${a_file} ]; then
          an_allright="False"
          a_bad_file=${a_file}
          break
      fi
  done
     
  if [ "${an_allright}" = "False" ]; then
      process_error "There is no '${a_bad_file}' file, in output folder '${an_output_dir}'"
  fi  

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_script test_hook


#-----------------------------------------------------------------------------------------
