#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./s3.sh


#-----------------------------------------------------------------------------------------
test()
{
  echo "********************************************************************************"
  echo $0

  a_script_name=`basename $0`
  prepare_testing_data && a_study_name1=`get_result`
  create_study && a_study_name2=`get_result`
  a_begin_study_name=`study_name_starts_with`
  
  process_script "amazon_ls.py --debug | grep -e ${a_study_name1} -e ${a_study_name2} | xargs amazon_rm_study.py --debug"

  bash -c "amazon_ls.py --debug 2>log.check_ls_pipe_rm_studies 1>/dev/null"
  count_entrances=`fgrep -c -e ${a_study_name1} -e ${a_study_name2} log.check_ls_pipe_rm_studies`
  rm log.check_ls_pipe_rm_studies
  if [ ${count_entrances} -ne 0 ]; then
      cat log.${a_script_name}
      rm log.${a_script_name}
      echo "--------------------------------------------------------------------------------"
      echo " ERROR : There is study named ${a_study_name1} or ${a_study_name2} ( may be both ) in the s3 "
      echo "--------------------------------------------------------------------------------"
      exit -1
  else
      rm_from_studies ${file_studies_starts}_ ${a_study_name1}
      rm_from_studies ${file_studies_starts}_ ${a_study_name2}
  fi

  echo '----------------------------------- OK -----------------------------------------'
}

#-----------------------------------------------------------------------------------------
run_script test


#-----------------------------------------------------------------------------------------
