#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. s3.sh


#-----------------------------------------------------------------------------------------
testing_download_file()
{
  a_script_name=`basename $0`
  a_study_name=`prepare_testing_data`
  an_output_dir=${case_dir}.out
  a_list_filenames=`create_list_filenames_in_casedir`
  a_downloading_file=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 2 ]" `

  echo "-------------------- Running \"${a_path_script}/${a_script_name}\" ----------------------"
  a_testing_script="amazon_download.py --study-name=${a_study_name} --located-files=${a_downloading_file} --output-dir=${an_output_dir} --fresh --debug"
  ${a_testing_script} > log.${a_script_name} 2>&1

  if [ $? -ne 0 ]; then
     echo ''
     echo ''
     echo "--------------------------------------------------------------------------------"
     echo "An error have appeared during execution of"
     echo "${a_testing_script}" 
     echo "--------------------------------------------------------------------------------"
     echo ''
     echo ''
     cat log.${a_script_name}
     rm log.${a_script_name}
     exit -1
  else
     if [ -f ${an_output_dir}/${a_downloading_file} ]; then
        echo '----------------------------------- OK -----------------------------------------'
     else
        echo ''
        echo ''
        echo "--------------------------------------------------------------------------------"
        echo " ERROR : There is no downloading file '${a_downloading_file}' , in '${an_output_dir}' folder "
        echo "--------------------------------------------------------------------------------"
        echo ''
        echo ''
        rm log.${a_script_name}
        exit -1
     fi
  fi  
}


#-----------------------------------------------------------------------------------------------------------------------
run_script testing_download_file
