#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./old_api.sh


#-----------------------------------------------------------------------------------------
a_list_studies=''
for an_old_api_verion in ${TEST_CLOUDFLU_LIST_OLD_API} ; do
  if [ -f ${TEST_CLOUDFLU_FILE_STUDIES_STARTS}_${an_old_api_verion} ] ; then 
     a_list_studies="`cat ${TEST_CLOUDFLU_FILE_STUDIES_STARTS}_${an_old_api_verion}` ${a_list_studies}"
     rm ${TEST_CLOUDFLU_FILE_STUDIES_STARTS}_${an_old_api_verion}
  fi
done

if [ "x${a_list_studies}" != "x" ] ; then
    cloudflu-study-rm ${a_list_studies} # to use muti-threading capabilities
fi

rm -rf ${TEST_CLOUDFLU_CASE_DIR_NAME}.out *~ log.*


#-----------------------------------------------------------------------------------------
