#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
. old_api.sh


#-----------------------------------------------------------------------------------------
for an_old_api_verion in ${a_list_old_api};do
  if [ -f ${file_studies_starts}_${an_old_api_verion} ]; then 
     a_list_studies=`cat ${file_studies_starts}_${an_old_api_verion}`
     if [ "x${a_list_studies}" != "x" ]; then
        amazon_rm_study.py ${a_list_studies}
     fi
     rm ${file_studies_starts}_${an_old_api_verion}
  fi
done
rm -rf ${a_case_dir_name}.out
rm -f log.*
rm -f *~


