#!/bin/bash

#--------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./old_api.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0 "'${1}'"

  a_script_name=`basename $0`
  an_old_api_number=${1}
  prepare_new_testing_data ${an_old_api_number} && a_study_name=`get_result`
  
  an_output_dir=${case_dir}.out

  process_script "amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --fresh" ${an_old_api_number}
   
  an_abspath_files=`python -c "import os; print os.path.abspath(\"${case_dir}\")"`
  a_differences=`diff -r -q -i -x "*~" ${case_dir} ${an_output_dir}${an_abspath_files}`
  if [ "x${a_differences}" != "x" ]; then
      process_error "There are differences between '${case_dir}' and '${an_output_dir}${an_abspath_files}':\n${a_differences}" ${an_old_api_number}
  else
      unregister_study ${file_studies_starts}_${an_old_api_number} ${a_study_name}
  fi

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_old_api_script test_hook 


#-----------------------------------------------------------------------------------------
