#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. old_api.sh


#-----------------------------------------------------------------------------------------
testing_ls_old_api_studies()
{
  a_script_name=`basename $0`
  an_old_api_number=$1

  a_study_name=`prepare_testing_data ${an_old_api_number}`

  echo "---- Running \"${a_path_script}/${a_script_name}\" api_version=\"${an_old_api_number}\" -----"
  a_testing_script="amazon_ls.py --debug"
  ${a_testing_script} > log.${a_script_name}_${an_old_api_number} 2>&1

  if [ $? -ne 0 ] ; then
     echo ''
     echo ''
     echo "--------------------------------------------------------------------------------"
     echo "An error have appeared during execution of" 
     echo ${a_testing_script}
     echo "--------------------------------------------------------------------------------"
     echo ''
     echo ''
     cat log.${a_script_name}_${an_old_api_number}
     rm log.${a_script_name}_${an_old_api_number}
     exit -1
  else
     count=`fgrep -c "${a_study_name}" log.${a_script_name}_${an_old_api_number}`
     if [ ${count} -gt 0 ] ; then 
        echo '----------------------------------- OK -----------------------------------------'
        `remove_log_prepare_test_case`
        echo ''
     else
        echo ''
        echo ''
        echo "--------------------------------------------------------------------------------"
        echo " ERROR : There is no '${a_study_name}' study in the s3 "
        echo "--------------------------------------------------------------------------------"
        echo ''
        echo ''
        cat log.${a_script_name}_${an_old_api_number}
        rm log.${a_script_name}_${an_old_api_number}
        exit -1
     fi   
  fi
}


#-----------------------------------------------------------------------------------------
run_old_api_script testing_ls_old_api_studies


