#!/bin/bash

#----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. common.sh


#-----------------------------------------------------------------------------------------
testing_ls_old_api_studies()
{
  an_old_api_number=$1
  `remove_log_prepare_test_case`
  a_study_name=`prepare_testing_data ${an_old_api_number}`

  echo "------------------- Testing amazon_ls \"${an_old_api_number}\" api studies ----------------------"
  amazon_ls.py --debug > log.amazon_ls_old_api_study 2>&1

  if [ $? -ne 0 ] ; then
     echo "An error have appeared during execution of amazon_ls.py" 
     cat log.amazon_ls_old_api_study
     rm log.amazon_ls_old_api_study
     exit -1
  else
     count=`fgrep -c "${a_study_name}" log.amazon_ls_old_api_study`
     if [ ${count} -gt 0 ] ; then 
        echo '----------------------------------- OK -----------------------------------------'
        `remove_log_prepare_test_case`
        echo ''
     else
        echo " ERROR : There is no '${a_study_name}' study in the s3 "
        rm log.amazon_ls_old_api_study
        exit -1
     fi   
  fi
}


#-----------------------------------------------------------------------------------------
for an_api in ${a_list_old_api}
do
  testing_ls_old_api_studies ${an_api}
done

