#!/bin/bash

#-----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
cd ${0%/*} || exit 1 # run from this directory
source ./old_api.sh


#-----------------------------------------------------------------------------------------
test_hook()
{
  echo "********************************************************************************"
  echo $0 "'${1}'"

  a_script_name=`basename $0`
  an_old_api_number=${1}
  prepare_testing_data ${an_old_api_number} && a_study_name=`get_result`

  an_output_dir=${case_dir}.out
  an_abspath_files=`python -c "import os; print os.path.abspath(\"${case_dir}\")"`

  process_script "amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --fresh" ${an_old_api_number}

  a_list_filenames=`create_list_filenames_in_casedir`
  an_allright="True"
  for a_file in ${a_list_filenames} ; do
      if [ ! -f ${an_output_dir}/${an_abspath_files}/${a_file} ]; then
          an_allright="False"
          a_bad_file=${a_file}
          break
      fi
  done

  if [ "${an_allright}" = "False" ]; then
      process_error "There is no '${a_bad_file}' file, in output folder '${an_output_dir}'" ${an_old_api_number}
  fi

  echo '----------------------------------- OK -----------------------------------------'
}


#-----------------------------------------------------------------------------------------
run_old_api_script test_hook


#-----------------------------------------------------------------------------------------


