#!/bin/bash

#-----------------------------------------------------------------------------------------
## Copyright 2010 Alexey Petrov
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author : Andrey Simurzin
##


#-----------------------------------------------------------------------------------------
#source common function
. old_api.sh


#-----------------------------------------------------------------------------------------
testing_download_old_api_study()
{
  a_script_name=`basename $0`
  an_old_api_number=$1
  `remove_log_prepare_test_case`
  a_study_name=`prepare_testing_data ${an_old_api_number}`

  an_output_dir=${case_dir}.out
  an_abspath_files=`python -c "import os; print os.path.abspath(\"${case_dir}\")"`

  echo "-- Running \"${a_path_script}/${a_script_name}\" api_version=\"${an_old_api_number}\" ---"
  
  a_testing_script="amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --enable-fresh --debug "
  ${a_testing_script} > log.${a_script_name}_${an_old_api_number} 2>&1

  if [ $? -ne 0 ]; then
     echo "An error have appeared during execution of " 
     echo ${a_testing_script}
     echo "--------------------------------------------------------------------------------"
     cat log.${a_script_name}_${an_old_api_number}
     rm log.${a_script_name}_${an_old_api_number}
     exit -1
  else
     a_list_filenames=`create_list_filenames_in_casedir`
     an_allright="True"
     for a_file in ${a_list_filenames}
     do
        if [ ! -f ${an_output_dir}/${an_abspath_files}/${a_file} ]; then
           an_allright="False"
           a_bad_file=${a_file}
           break
        fi
     done
     if [ "${an_allright}" = "False" ]; then
        echo " ERROR : There is no '${a_bad_file}' file , in output folder  '${an_output_dir}'. "
        echo "--------------------------------------------------------------------------------"
        rm log.${a_script_name}_${an_old_api_number}
        exit -1     
     else
        echo '----------------------------------- OK -----------------------------------------'
        `remove_log_prepare_test_case`
        echo ''
     fi
  fi
}


#-----------------------------------------------------------------------------------------
run_old_api_script testing_download_old_api_study ${an_api}

