#!/bin/sh

#--------------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # run from this directory
set -x


#--------------------------------------------------------------------------------------
echo `wmake exe` > ./wmake.log

if [ $? != 0 ] ; then
    exit 1
fi
 
# To extract the target application name
application=`cat ./Make/files | grep SEXE | sed -e"s%\([^/]*\)/\(.*\)%\2%g"`

echo ${application}


#--------------------------------------------------------------------------------------
